# 說明
# 本 Dockerfile 用於建立一個容易受攻擊的 Ubuntu 環境，專為學術演示和學習目的設計。
# 使用前，請確保 boxInitialize.sh 腳本位於同一目錄下。
# 在終端機中執行以下指令來構建 Docker 映像：docker build -t vulnerable_ubuntu .
# 構建完成後，可以使用以下指令來啟動容器：docker run -p 22:22 -d vulnerable_ubuntu
# 這樣將映射容器的 22 端口到本機的 22 端口，以便進行 SSH 連線。

# 設定基底容器
FROM ubuntu:latest

# 更新Ubuntu套件清單，確保安裝時使用最新版本的軟體
RUN apt-get update && apt-get install -y --no-install-recommends \
  openssh-server \
  ca-certificates \
  dos2unix \
  && rm -rf /var/lib/apt/lists/*

# 初始化設定
# 複製 boxInitialize.sh 腳本到容器的 /root 目錄
COPY boxInitialize.sh /root/boxInitialize.sh
# 轉換 boxInitialize.sh 從 DOS 格式到 UNIX 格式，避免執行腳本時發生問題
RUN dos2unix /root/boxInitialize.sh
# 給予 boxInitialize.sh 執行權限
RUN chmod +x /root/boxInitialize.sh
# 執行 boxInitialize.sh 來設定 Ubuntu
RUN /root/boxInitialize.sh

# 設定 SSH 服務
# 設定容器啟動時自動啟動 SSH 服務
CMD ["/usr/sbin/sshd", "-D"]

# 設定網路
# 開放 22 端口以啟用 SSH 連線
EXPOSE 22
